### ISSUE TITLE
Some scripts on Windows throws ImportError: cannot import name EX_OK

### ISSUE THREAD

**Issue by Geevarghese** [CiscoDevNet/cosc-learning-labs#60] opened 2015-06-04 12:13 UTC
Following scripts are giving ImportError: cannot import name EX_OK In windows.
01_device_connect.py
01_inventory_dismount_atomic.py
03_interface_properties.py
04_routes.py
04_static_route_capability.py
04_static_route_delete.py
04_static_route_json.py
04_static_route_suite.py
restore_network_state.py
In Ubuntu all works without error.

**Comment by kjarrad** [comment] 2015-06-11 12:36
Duplicate of Issue #68

**Closed by kjarrad** 2015-06-11 12:36 UTC
Labels: duplicate
